### ISSUE TITLE
Akce se na stránce chapteru špatně řadí

### ISSUE THREAD

**Issue by lordwiccar** [gugcz/web-frontend#11]
Akce se řadí nevhodně. Akce, která je první vytvořená je na stránce eventu velká a s náhledem textu, akce vytvořená jako druhá je pak menší. Problém je, že později vytvořená akce může probíhat dříve a tak by měla být tou větší... Jako se teď stalo mě: https://gug.cz/chapter/gxg-chomutov

**Comment by Horm** [comment]
Mělo by být opraveno, Firebase API order by není order by... 😢
