### ISSUE TITLE
Nenačítání obrázků partnerů

### ISSUE THREAD

**Issue by HormCodes** [gugcz/web-frontend#19]
Prohlížeč zruší requesty na načítání obrázků. Projevuje se to hlavně u partnerů, ale také občas u log skupin. Nutná oprava. 

Nemohlo by to být tím, že je tam hromada requestů na profilové fotky orgů? 
![image](https://user-images.githubusercontent.com/10332399/56456773-4e711980-6371-11e9-837b-f0d70c1f3769.png)

**Comment by ryzizub** [comment]
Jedná se o velké množství requestů. Navrhuji přidat na web lazy loading (minimálně pro obrázky orgů)

**Comment by bartusek27** [comment]
Částečně vyřešeno v #32, kde je použit u obrázků parametr loading="lazy" - to funguje co vím v Chromu od verze 76 ale nevím, jestli ve Firefoxu.
Obrázky se tedy pro Chrome budou načítat líně :), pro podporu dalších prohlížečů bychom museli přidat nějaký polyfill nebo něco, co by potřebovalo trochu práce...

**Comment by ryzizub** [comment]
Vyřešeno by @vojtabiberle v PR #35
