### ISSUE TITLE
Rebranding GDG a GBG

### ISSUE THREAD

**Issue by Horm** [gugcz/web-frontend#20]
Provést rebranding loga GDG a GBG. 

Jde o hlavní stránku, favicony a stránky chapteru...

**Comment by Horm** [comment]
Chybí ještě favicony. Vyhazuji otázku zda zanechat dynamické favicony nebo to neřešit a mít tam celogug, když už máme vlastní brand...

**Comment by leosprikryl** [comment]
Osobně si myslím, že dynamické favicony jsou zbytečné. Dal bych tam klidně celogug.

**Comment by ryzizub** [comment]
@Horm V mergi #28 jsou updatnuté v app/assets/images/favicons i favicony pro GDG a GBG, nebo je to ještě někde jinde?
Jsem ale pro, nad celou stránku nechat pouze faviconu GUG, na to ale asi novou issue

**Comment by Horm** [comment]
Byla tam cache, ale když už byly nové loga na webu, tak jsem myslel, že jsi zapomněl a neprozkoumám to. Omlouvám se za re-open, moje chyba... 🤦‍♂

**Comment by ryzizub** [comment]
> Byla tam cache, ale když už byly nové loga na webu, tak jsem myslel, že jsi zapomněl a neprozkoumám to. Omlouvám se za re-open, moje chyba...

V pohodě :+1: myslel jsem si to
